### ISSUE TITLE
ul is an existing command in /usr/bin

### ISSUE THREAD

**Issue by chrisidefix** [apaszke/termtile#10]
`ul` is a pre-existing command-line utility you can find at `/usr/bin/ul`. It's probably not used a lot, but it's worth being aware of.

**Comment by apaszke** [comment]
I know. `install.sh` is too and asks you if you want to overwrite it. I have never heard of it before, so I hope that it's not too popular. I'm more worried about `ll` :confused: Thanks for the issue anyway :+1:
