### ISSUE TITLE
tmux

### ISSUE THREAD

**Issue by 0x6a68** [apaszke/termtile#11]
why not [tmux](https://github.com/tmux/tmux)?

**Comment by IonicaBizau** [comment]
I think `termtile` is more into managing the terminal window gui, while `tmux` is a multiplexer. I use `tmux` a lot! I like it!

Hey @apaszke, glad to see your project [on the trending repos pages](https://github.com/explore?since=daily). :smile: :clap: :tada:

**Comment by apaszke** [comment]
@IonicaBizau Exactly :+1:
Hahaha thanks I wasn't even aware of it :bowtie: :tada:
