### ISSUE TITLE
Problem omitting shortcut in bash

### ISSUE THREAD

**Issue by ezig** [apaszke/termtile#15]
Tried to install this for my bash shell and found that `ul` is already an alias (as #10 pointed out). I tried to enter a new line to omit it for now, but the prompt kept coming back until I pressed return several times in a row. Am I misunderstanding what "blank" means or is something weird going on? Attaching a screenshot of what it looked like:

<img width="440" alt="screenshot 2015-08-17 21 05 08" src="https://cloud.githubusercontent.com/assets/6855546/9320068/c88ac844-4523-11e5-83e4-fb0d6bd6d4c7.png">

**Comment by seclorum** [comment]
Just wanted to confirm that I had this issue as well .. 

```
$ uname -a && brew -v
Darwin w1x8 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
Homebrew 0.9.5
```

**Comment by apaszke** [comment]
No, blank is just return.
That's strange. It works for me :confused:
Could you please post your `bash --version`?

**Comment by apaszke** [comment]
I've found the problem. I forgot that variables are global by default in bash. Could you please check it now?

**Comment by seclorum** [comment]
Can confirm - its fixed.  I would like to suggest that you add a "t_" prefix to all aliases, however .. too many of these collide with aliases I already have, such as 'll', 'ul', 'up', 'max', etc.  Adding a prefix would be worthwhile, imho ..

**Comment by apaszke** [comment]
I know that there are lots of problems with prefixes and I'm considering asking for a leader key in `install.sh`. So if you type `t_` it will prefix all commands with it

**Comment by apaszke** [comment]
`install.sh` asks you for a prefix now :blush:
