### ISSUE TITLE
Not sure if possible to fix, but doesnt work with borderless iterm2

### ISSUE THREAD

**Issue by bryanbecker** [apaszke/termtile#18]
The error message is:

```
/Users/me/.termtile/tile.scpt: execution error: iTerm2 got an error: Can’t get window 0. (-1728)
```

**Comment by apaszke** [comment]
You mean borderless like in here: https://github.com/Nasga/iterm2-borderless?

**Comment by apaszke** [comment]
I've compiled iTerm2 with modification from the repo above and everything works just fine. Could you please tell me what did you modify, so I could reproduce the bug?

**Comment by bryanbecker** [comment]
Let me recompile my iTerm2 and get back to you.  I don't remember the exact steps I took at the time.

**Comment by bryanbecker** [comment]
I can confirm that pulling the latest version of iTerm2 from their repo, and re-applying the borderless patch solves the issue.
