### ISSUE TITLE
sn gives "The variable _currentScreen is not defined" error

### ISSUE THREAD

**Issue by ansel1** [apaszke/termtile#19]
Full error is:

```
~/.termtile/changeScreen.scpt: execution error: The variable _currentScreen is not defined. (-2753)
```

I'm not fluent in applescript, but I looked at changeScreen.scpt on master, and it did look like that variable is used on line 24 before it's been declared anywhere.

**Comment by apaszke** [comment]
Right, I've introduced this bug in fullscreen branch :confused:
Sorry for that, I've pushed a fix
