### ISSUE TITLE
Full screen?

### ISSUE THREAD

**Issue by markmontymark** [apaszke/termtile#2]
What about two more options:
- fs = fullscreen, like fullscreen video, no window border or toolbar
- mx = maximize, full width but still showing toolbar

**Comment by apaszke** [comment]
So mx is just like fs, but doesn't create a new desktop, right?

**Comment by markmontymark** [comment]
right, that was what i was thinking.  or, in osx window manager terms, mx = the + icon in window toolbar , and fs = the opposing arrows icon (top-right corner in toolbar)

**Comment by apaszke** [comment]
I like it. I'll try to add it :+1:

**Comment by markmontymark** [comment]
woot!  fs works perfect for me.

**Comment by apaszke** [comment]
It's great to hear that :tada:
