### ISSUE TITLE
iTerm issues on multiple screens

### ISSUE THREAD

**Issue by titipata** [apaszke/termtile#21]
When I have external screen or monitor, the command will bring terminal screen back to my laptop. It would be great if terminal can move within monitor that I currently use (either laptop or external screen).

**Comment by apaszke** [comment]
Could you please post some more details of your setup please? Do you have the newest version of termtile?
Some of the initial releases didn't support many displays, but it should work now. I've tested it on my MBP with external display and everything worked just fine. Other people have also reported that it's ok now.

**Comment by titipata** [comment]
Yeah definitely @apaszke. 

I use Mac 15" early 2013 model. My OS is Yosemite 10.10.4. The monitor that I use is Dell U2415. I just re-install termtile so it should be the latest version. Basically, when I move terminal to Dell screen and type `ul` (for example), it will move my terminal screen back to my Mac. Not sure if it only occurs on my computer or not.

**Comment by apaszke** [comment]
Multi-screen support required me to do some hacks and it's a bit simplified right now. It specifies to which screen the window belongs by looking at its upper left corner. Is the window fully on your Dell screen?

**Comment by titipata** [comment]
Yeah, the whole terminal screen is in Dell monitor. The arrangement of my screen is as follows
![arrangement](https://cloud.githubusercontent.com/assets/8295838/9370137/904a51cc-4693-11e5-9683-0d1622bacd08.png).

**Comment by apaszke** [comment]
Thanks for the email with details. I set up my display arrangement just like you did and my terminal worked fine. Then, I noticed that you're using iTerm and when I launched it, it all broke down... I'll try to take a look at it as soon as I can, but I will be away now, so you can probably expect a fix during the weekend. Sorry :confused:

**Comment by titipata** [comment]
No rush at all @apaszke! It's a really great tool to have on terminal. Thanks for noting the issue.

**Comment by apaszke** [comment]
Wow, this is so weird. Is seems that iTerm responds to changing bounds in a completely different way... I'll have to handle it separately :confused:

**Comment by apaszke** [comment]
I've pushed a new version to `master`. The bugs you're experiencing should be fixed. Please let me know if it's ok to close this issue :relaxed:

**Comment by titipata** [comment]
I tested it. I think it works for me! Thanks so much @apaszke. It's been a great help. Should we close the issue?

**Comment by apaszke** [comment]
Yeah. Apparently the terminal ignores the display's vertical offset, but all other apps do care about it. Guess what was I using while writing previous implementation :stuck_out_tongue:
Great to hear that it's all good now!
