### ISSUE TITLE
Change "*.applescript" to "*.script" in README

### ISSUE THREAD

**Issue by sg-s** [apaszke/termtile#26]
because that's what the actual files are called...

**Comment by apaszke** [comment]
I'm not aware of any projects using AppleScript and saving files with `.script` extenstion. You can type `applescript` into GitHub search and check yourself that everyone uses `.applescript`. I'm also attaching a screenshot from wikipedia, which lists `.scpt, .AppleScript` as AppleScript extensions :blush: 

<img width="280" alt="screen shot 2015-08-24 at 22 03 27" src="https://cloud.githubusercontent.com/assets/4583066/9451017/73daf3a8-4aac-11e5-8b6f-5e4edff9a0be.png">

**Comment by sg-s** [comment]
thank you for the detailed reply, and i'm sorry for my initially curt suggestion. what i mean is this:

in the readme, you refer to your different script files using an extention, as so:
```
tile.applescript
```

i suggested changing the extension to match the file name.
