### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by moxdev** [apaszke/termtile#28]
This looks like an awesome feature Id love to use but I followed the instructions and it doesn't seem to be working on my machine. Im using iTerm2 and oh-my-zsh on Yosemite. I can see all the aliases in my ~/.zshrc file but when I try to use the alias noting happens it just starts a new line. Any tips for troubleshooting?

Also Im using iTerm Build 2.1.1 and did not see this option in my Profile>Window:
(Tip: enable Command key option in Preferences > Profiles > Window, so you'll see the keyboard shortcut which jumps to a particular window)

Any help would be greatly appreciated!

**Comment by apaszke** [comment]
Hm, that's strange. I've just checked iTerm 2.1.1 with zsh on Yosemite and it works. Maybe it's oh-my-zsh which is messing things up. Could you please paste the output of `which ll` or try to `source ~/.zshrc`.

Regarding the preferences, as far as I know this option exists only in Terminal.app :confused:

**Comment by moxdev** [comment]
I did try sourcing `.zshrc` also tried restarting several times but no change. All of the aliases show up in `.zshrc` but its like the script doesnt run nothing happens just goes to a new line. Maybe I should use Terminal to reinstall instead of using oh-my-zsh?

`which ll`
`ll: aliased to osascript ~/.termtile/tile.scpt left`

**Comment by moxdev** [comment]
Thanks for your help apaszke I finally got it working. Apparently there was a pending XCode terms of service agreement that was wreaking havoc on my terminal environment. Anyway the scripts now work beautifully thanks for putting this together!

**Comment by apaszke** [comment]
It's good to hear that it works now. I forgot about checking the Xcode terms before compilation! I'll have to add it to the installation script. Thanks!
