### ISSUE TITLE
All commands throwing an error on El capitan beta (15A243d ) and iTerm Build 2.9.20150805-nightly

### ISSUE THREAD

**Issue by Nishith** [apaszke/termtile#4]
~/.termtile/tile.scpt: execution error: Finder got an error: Can’t get bounds of window of desktop. (-1728)

**Comment by apaszke** [comment]
Do you have desktop enabled? Could you please post output from the following commands:

``` bash
defaults read com.apple.finder QuitMenuItem
defaults read com.apple.finder CreateDesktop
```

**Comment by epicbagel** [comment]
```
defaults read com.apple.finder QuitMenuItem
2015-08-17 16:01:25.605 defaults[82252:6909771] 
The domain/default pair of (/Users/jon/Library/Preferences/com.apple.finder, QuitMenuItem) does not exist
```

And

```
defaults read com.apple.finder CreateDesktop
0
```

**Comment by apaszke** [comment]
It's probably because `CreateDesktop` is set to 0. You can try to change it with 

`defaults write com.apple.finder CreateDesktop -bool true`

I'll have to rewrite checking screen sizes anyway, so it won't depend on AppleScript and Finder anymore. Stay tuned to #6

**Comment by Nishith** [comment]
For me it is:
defaults read com.apple.finder QuitMenuItem  -> 1
defaults read com.apple.finder CreateDesktop -> 0

Thanks,
Nishith

From:  Adam Paszke
Reply-To:  apaszke/termtile
Date:  Monday, August 17, 2015 at 7:41 AM
To:  apaszke/termtile
Cc:  Nishith Nand
Subject:  Re: [termtile] All commands throwing an error on El capitan beta (15A243d ) and iTerm Build 2.9.20150805-nightly (#4)

Do you have desktop enabled? Could you please post output from the following commands:

defaults read com.apple.finder QuitMenuItem
defaults read com.apple.finder CreateDesktop

**Comment by Nishith** [comment]
Setting CreateDesktop to true fixes the issue. Thanks.

**Comment by apaszke** [comment]
@Nishith could you please reset CreateDesktop to 0 and check the newer version? It no longer depends on Finder so it should work anyway

**Comment by Nishith** [comment]
Works now with CreateDesktop set to 0. Also, works better with multiple monitors now. Thanks for the change.

**Comment by apaszke** [comment]
Awesome :smiley:
