### ISSUE TITLE
`ll` is a common alias for `ls -l`

### ISSUE THREAD

**Issue by enedil** [apaszke/termtile#5]
As in title, `ll` being already an alias this conflicts with `ll` as fill to left.

**Comment by apaszke** [comment]
I know, but if you want to use another alias you can specify it directly in `install.sh` (it prompts for your proposition after denying the overwrite). I wanted to be consistent with `rr`.
Do you have a better idea for this alias?

**Comment by kennyg** [comment]
I'm running into the same issue. I think `fl` for fill left and `fr` for fill right would be a better idea.

**Comment by apaszke** [comment]
I like `fl` and `fr` idea but `ll` and `rr` are easier to type for me. I've added a check to `install.sh`, which suggests you @kennyg's aliases if `ll` is already used.
