### ISSUE TITLE
Doesn't work for multiple screens. 

### ISSUE THREAD

**Issue by lei-cao** [apaszke/termtile#6]
it Only resizes against the main screen.

**Comment by zshbleaker** [comment]
And some commands like cen and big act weird for multiple or triple screen.

**Comment by zilionis** [comment]
:+1:

**Comment by suevalov** [comment]
+1

**Comment by apaszke** [comment]
I'll check it, thanks. I've heard that it's a bit harder to make applescript work with multiple screens, but I'll do my best :blush:

**Comment by apaszke** [comment]
I don't think it's possible to differentiate between different screens with just AppleScript. I'll add a small utility program. Finally a reason to learn swift :smiley:

It might take a while, sorry.

**Comment by noahmatisoff** [comment]
+1 thanks @apaszke

**Comment by apaszke** [comment]
Good news, the NSScreen API is really easy to use so I've already hacked an initial version of this utility :grin: I just need to rethink how to calculate the positions properly regardless of the screen grid.

**Comment by noahmatisoff** [comment]
Nice!  I'd imagine the vast majority of users have multiple displays so this will make this usable for that majority.

**Comment by apaszke** [comment]
Hey, I've got a quick question. How would you like it to work? There are 2 options:
1. Always keep the area where the dock can appear empty
2. Resize the windows checking if the dock is visible in the current screen (so use the full vertical area when it's on another one, but when it's on the same screen then subtract it's height)

I'm wondering if the 2nd option wouldn't be a bit strange to use. And it still doesn't stop the dock from occluding the terminal if it changes location :confused: 
What do you think?

**Comment by apaszke** [comment]
I've pushed a `multi-screen` branch. It's definitely not ready for master, but it works! :blush:

Please checkout, install it, and let me know if there are any serious bugs you can find right now!

**Comment by apaszke** [comment]
`multi-screen` branch is merged into master. It works for my two screens regardless of how funny I position them in the display settings. :tada:
Please let me know if it's working fine for you too!

**Comment by suevalov** [comment]
Thanks, works like a charm!
